# Site settings
title: Ty Magnin's personal page
email: tyler.magnin@gmail.com
description: "Director of Marketing - Appcues"
baseurl: ""
url: "http://ourbeachplumwedding.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
