# Site settings
title: Ty Magnin | CEO at Animalz
email: ty.magnin@gmail.com
description: "Ty Magnin is the CEO at Animalz, a content marketing agency, and a software marketing leader. He has built teams, audience, and pipeline at companies like Appcues, UiPath, and Work Market."
baseurl: ""
url: "http://tymagnin.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
