# Site settings
title: Ty Magnin
email: ty.magnin@gmail.com
description: "Director of Marketing - Appcues"
baseurl: ""
url: "http://tymagnin.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
